# [46장] 제너레이터와 async/await

### 46.1 제너레이터란?
코드 블록의 실행을 일시 중지했다가 필요한 시점에 재개할 수 있는 특수한 함수(ES6)
#### 제너레이터와 일반 함수의 차이
1. 제너레이터 함수는 함수 호출자에게 함수 실행의 제어권을 양도할 수 있다. → `yield`
2. 제너레이터 함수는 함수 호출자와 함수의 상태를 주고받을 수 있다.
3. 제너레이터 함수를 호출하면 제너레이터 객체를 반환한다. → 함수 코드 실행X

### 46.2 제너레이터 함수의 정의
- `function*` 키워드로 선언
  - 에스터리스크(*)의 위치는 function 키워드와 함수 이름 사이 어디 위치하든 상관없음
- 하나 이상의 `yield` 표현식 포함
- 화살표 함수로 정의 불가능
- 생성자 함수로 호출 불가능

```
function* getDecFunc() {
  yield 1;
}

const genExpFunc = function* () {
  yield 1;
}

const obj = {
  * genObjMethod() {
    yield 1;
  }
}

class MyClass {
  * genClsMethod() {
    yield 1;
  }
}
```

### 46.3 제너레이터 객체
- 제너레이터 함수 호출 시 함수 코드 블록을 실행하는 것이 아니라 제너레이터 객체를 생성해 반환한다.
- 제너레이터 객체는 이터러블이면서 동시에 이터레이터
- `Symbol.iterator` 상속
- `next`, `return`, `throw` 메서드 소유
  - `return`, `throw` 메서드는 이터레이터에는 없는 메서드

메서드 | 호출 시
--|--
next | 제너레이터 함수의 yield 표현식까지 코드 블록 실행 → `{value: yield된 값, done: false}` 이터레이터 리절트 객체 반환
return | `{value: 인수로 전달받은 값, done: true}` 이터레이터 리절트 객체 반환
throw | 인수로 전달받은 에러 발생, `{value: undefined, done: true}` 이터레이터 리절트 객체 반환

```
function* genFunc() {
  try {
    yield 1;
    yield 2;
    yield 3;
  } catch (e) {
    console.error(e);
  }
}

const generator = genFunc();

console.log(generator.next());          // {value: 1, done: false}
console.log(generator.return('End!'));  // {value: "End!", done: true}
console.log(generator.throw('Error!')); // {value: undefined, done: true}
```

### 46.4 제너레이터의 일시 중지와 재개
- `yield` 키워드와 `next` 메서드를 통해 실행을 일시 중지했다가 필요한 시점에 재개할 수 있다.
- 코드 블록의 모든 코드를 일괄 실행하지 않고 yield 표현식까지만 실행

#### yield
- 제너레이터 함수의 실행 일시 중지
- yield 키워드 뒤에 오는 표현식의 평가 결과를 제너레이터 함수 호출자에게 반환

#### 실행 과정
```
next 메서드 호출 → yield 표현식까지 실행 → 일시 중지 → 함수의 제어권이 호출자로 양도됨 → next 메서드 호출 → 일시 중지된 코드부터 실행 재개 → yield 표현식까지 실행 → 일시 중지

generator.next() → yield → generator.next() → yield → ... → generator.next() → return
```

#### next
- 인수 전달 가능 → yield 표현식을 할당받는 변수에 할당
```
function* genFunc() {
  const x = yield 1;
  const y = yield (x + 10);
  return x + y;
}

const generator = genFunc(0);
let res = generator.next();   // 처음 호출하는 next에는 인수 전달 X → 전달해도 무시됨
console.log(res);             // {value: 1, done: false}

res = generator.next(10);     // x = 10
console.log(res);             // {value: 20, done: false}

res = generator.next(20);     // y = 20, x + y = 30
console.log(res);             // {value: 30, done: true}
```

### 46.5 제너레이터의 활용
#### 이터러블의 구현
```
// 무한 이터러블을 생성하는 제너레이터 함수
const infiniteFibonacci = (function* () {
  let [pre, cur] = [0, 1];

  while (true) {
    [pre, cur] = [cur, pre + cur];
    yield cur;
  }
}());

// infiniteFibonacci는 무한 이터러블이다.
for (const num of infiniteFibonacci) {
  if (num > 10000) break;
  console.log(num); // 1 2 3 5 8...2584 4181 6765
}
```

#### 비동기 처리
```
// node-fetch는 node.js 환경에서 window.fetch 함수를 사용하기 위한 패키지다.
// 브라우저 환경에서 이 예제를 실행한다면 아래 코드는 필요 없다.
// https://github.com/node-fetch/node-fetch
const fetch = require('node-fetch');

// 제너레이터 실행기
const async = generatorFunc => {
  const generator = generatorFunc();

  const onResolved = arg => {
    const result = generator.next(arg);

    return result.done
      ? result.value
      : result.value.then(res => onResolved(res));
  };

  return onResolved;
};

(async(function* fetchTodo() {
  const url = 'https://jsonplaceholder.typicode.com/todos/1';

  const response = yield fetch(url);
  const todo = yield response.json();
  console.log(todo);
  // {userId: 1, id: 1, title: 'delectus aut autem', completed: false}
})());
```

### 46.6 async/await
제너레이터보다 간단하고 가독성 좋게 비동기 처리를 동기 처리처럼 동작하도록 구현할 수 있음(ES8)
→ 프로미스 기반
```
const fetch = require('node-fetch');

async function fetchTodo() {
  const url = 'https://jsonplaceholder.typicode.com/todos/1';

  const response = await fetch(url);
  const todo = await response.json();
  console.log(todo);
  // {userId: 1, id: 1, title: 'delectus aut autem', completed: false}
}

fetchTodo();
```

#### async
- 항상 프로미스 반환 → 명시적으로 반환하지 않아도 반환값을 resolve하는 프로미스 반환
- 클래스의 constructor 메서드는 async 메서드가 될 수 없음 → 반환값 인스턴스 !== 프로미스
```
async function foo(n) { return n; }
foo(1).then(v => console.log(v)); // 1

const bar = async function (n) { return n; };
bar(2).then(v => console.log(v)); // 2

const baz = async n => n;
baz(3).then(v => console.log(v)); // 3

const obj = {
  async foo(n) { return n; }
};
obj.foo(4).then(v => console.log(v)); // 4

class MyClass {
  async bar(n) { return n; }
}
const myClass = new MyClass();
myClass.bar(5).then(v => console.log(v)); // 5
```

#### await
- async 함수 내부에서 사용해야 함
- 프로미스가 settled 상태가 될 때까지 대기하다가 settled 상태가 되면 프로미스가 resolve한 처리 결과 반환
- 반드시 프로미스 앞에서 사용
- 개별적으로 수행되는 비동기 처리에 대해서는 await를 이용해서 순차적으로 처리하지 않아도 됨
```
const fetch = require('node-fetch');

const getGithubUserName = async id => {
  const res = await fetch(`https://api.github.com/users/${id}`);
  const { name } = await res.json();
  console.log(name); // Ungmo Lee
};

getGithubUserName('ungmo2');
```

#### 에러 처리
- `try-catch` 문으로 에러 처리
  ```
  const fetch = require('node-fetch');

  const foo = async () => {
    try {
      const wrongUrl = 'https://wrong.url';

      const response = await fetch(wrongUrl);
      const data = await response.json();
      console.log(data);
    } catch (err) {
      console.error(err); // TypeError: Failed to fetch
    }
  };

  foo();
  ```
- `Promise.prototype.catch` 후속 처리 메서드로 에러 처리: async 함수 내에서 catch 문으로 에러 처리를 하지 않으면 발생한 에러를 reject하는 프로미스 반환
  ```
  const fetch = require('node-fetch');

  const foo = async () => {
    const wrongUrl = 'https://wrong.url';

    const response = await fetch(wrongUrl);
    const data = await response.json();
    return data;
  };

  foo()
    .then(console.log)
    .catch(console.error); // TypeError: Failed to fetch
  ```